# -*- coding: utf-8 -*-
"""creditcard.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11qmoCkxhyv5_qEVEtyGX44W5E6-Jb1tb
"""

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report
from imblearn.over_sampling import SMOTE

df = pd.read_csv("/content/creditcard.csv")

df = df.dropna(subset=['Class'])

X = df.drop('Class', axis=1)
y = df['Class']

X['Amount'] = StandardScaler().fit_transform(X['Amount'].values.reshape(-1, 1))
X = X.drop('Time', axis=1)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

sm = SMOTE(random_state=42)
X_res, y_res = sm.fit_resample(X_train, y_train)

model = RandomForestClassifier(n_estimators=100, random_state=42)
model.fit(X_res, y_res)

y_pred = model.predict(X_test)

print("Classification Report:\n")
print(classification_report(y_test, y_pred))