# -*- coding: utf-8 -*-
"""Titanic.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ttr505nv6n24WZE5ErYcQvgzSbdcjxve
"""

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.ensemble import RandomForestClassifier
df = pd.read_csv('/content/tested.csv')
df = df[['Survived', 'Pclass', 'Sex', 'Age']]
df['Age'].fillna(df['Age'].median(), inplace=True)
le_sex = LabelEncoder()
df['Sex'] = le_sex.fit_transform(df['Sex'])
X = df[['Pclass', 'Sex', 'Age']]
y = df['Survived']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
model = RandomForestClassifier()
model.fit(X_train, y_train)
print("Enter passenger details:")
pclass = int(input("Pclass (1/2/3): "))
sex = input("Sex (male/female): ")
age = float(input("Age: "))
sex_encoded = le_sex.transform([sex])[0]
input_data = pd.DataFrame([[pclass, sex_encoded, age]], columns=X.columns)
prediction = model.predict(input_data)[0]
print("Prediction: The passenger", "survived " if prediction == 1 else "did NOT survive ")